#!/bin/sh
ssh root@favl.dk <<EOF
cd ~/hacker-news-backend/
git pull
npm install --production
docker build -t favl/hacker-news-clone .
docker login -u favl -p "${DOCKERHUB_PWD}"
docker push favl/hacker-news-clone:latest
docker logout
docker pull favl/hacker-news-clone:latest
docker stop hacker-news-backend
docker rm hacker-news-backend
docker run --name hacker-news-backend -d -p 8080:8080 favl/hacker-news-clone:latest
exit
EOF
